// Autogenerated by build.rs

pub const FILES: &'static [(&'static str, u32)] = &[
    ("proto/authentication.proto", 3394898568),
    ("proto/keyexchange.proto", 4121421153),
    ("proto/mercury.proto", 678333236),
    ("proto/metadata.proto", 1486248042),
    ("proto/pubsub.proto", 1342896749),
    ("proto/spirc.proto", 3741543556),
];
