[package]
name = "librespot-audio"
version = "0.1.0"
authors = ["Paul Lietar <paul@lietar.net>"]

[dependencies.librespot-core]
path = "../core"

[dependencies]
bit-set = "0.4.0"
byteorder = "1.0"
futures = "0.1.8"
lewton = "0.8.0"
log = "0.3.5"
num-bigint = "0.1.35"
num-traits = "0.1.36"
rust-crypto = "0.2.36"
tempfile = "2.1"

tremor = { git = "https://github.com/plietar/rust-tremor", optional = true }
vorbis = { version ="0.1.0", optional = true }

[features]
with-tremor = ["tremor"]
with-vorbis = ["vorbis"]
